# This file shoudln't be touched
# Database config is in settings.toml
# This is legacy because of gobuffalo/pop's hard requirement on this file

development:
   url: {{env "DATABASE_URL" }}

test:
  url: {{env "DATABASE_URL" }}

production:
  url: {{env "DATABASE_URL" }}